---
- name: Установить необходимые пакеты
  apt:
    name:
      - ocserv
    state: present
    update_cache: yes

- name: Включить IP-пересылку
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  become: yes

- name: Настроить правило NAT для VPN-сети
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ ocserv_vpn_subnet }}"
    out_interface: "{{ ocserv_network_interface }}"
    jump: MASQUERADE
  become: yes

- name: Сохранить iptables правила
  command: iptables-save
  register: iptables_rules
  become: yes

- name: Записать правила в файл
  copy:
    content: "{{ iptables_rules.stdout }}"
    dest: "/etc/iptables.rules"
    mode: '0644'
  become: yes

- name: Обеспечить загрузку iptables правил при старте
  copy:
    dest: /etc/network/if-pre-up.d/iptables_restore
    content: |
      #!/bin/sh
      /sbin/iptables-restore < /etc/iptables.rules
    mode: '0755'
  become: yes

- name: Создать каталог для SSL сертификатов
  file:
    path: /etc/ocserv/ssl
    state: directory
    mode: '0755'
  become: yes

- name: Сгенерировать самоподписанный SSL сертификат (если не существует)
  command: >
    openssl req -new -x509 -nodes -days 3650
    -subj "/CN={{ ansible_fqdn }}" -newkey rsa:2048
    -keyout /etc/ocserv/ssl/server-key.pem -out /etc/ocserv/ssl/server-cert.pem
  args:
    creates: /etc/ocserv/ssl/server-cert.pem
  become: yes

- name: Скопировать основной конфиг ocserv
  template:
    src: "ocserv.conf.j2"
    dest: "/etc/ocserv/ocserv.conf"
    mode: '0644'
  notify: Перезапуск ocserv

- name: Настроить локальных пользователей (если OIDC отключен)
  block:
    - name: Создать файл пользователей /etc/ocserv/passwd
      file:
        path: /etc/ocserv/passwd
        state: touch
        mode: '0600'

    - name: Добавить локальных пользователей в /etc/ocserv/passwd
      lineinfile:
        path: "/etc/ocserv/passwd"
        line: "{{ item.key }}:{{ item.value }}"
        create: yes
      with_dict: "{{ ocserv_local_users }}"
  when: not ocserv_enable_oidc

- name: Создать каталог конфигурации ocserv
  file:
    path: "/etc/ocserv/config-per-group"
    state: directory
    mode: '0755'

- name: Создать конфигурационные файлы для групп
  template:
    src: "group_config.j2"
    dest: "/etc/ocserv/config-per-group/{{ item.key }}"
    mode: '0644'
  with_dict: "{{ ocserv_groups }}"
  notify: Перезапуск ocserv

- name: Перезапустить ocserv
  systemd:
    name: ocserv
    state: restarted
    daemon_reload: yes
